export const lucideIcons = {
  income: [
    'Landmark',
    'DollarSign',
    'Euro',
    'PoundSterling',
    'BanknoteArrowDown',
    'JapaneseYen',
    'TrendingUp',
    'TrendingDown',
    'Gift',
    'Briefcase',
    'Laptop',
    'HandCoins',
    'Receipt',
    'PiggyBank',
    'PlusCircle',
    'KeyRound',
    'Tag',
    'Bitcoin',
  ],
  expenses: {
    houseAndBills: [
      'Home',
      'Building2',
      'HomePlus',
      'Zap',
      'Droplets',
      'Flame',
      'Signal',
      'Phone',
      'Tv',
      'Wrench',
      'Armchair',
      'Trash2',
      'Shield',
      'Sprout',
    ],
    food: [
      'ShoppingCart',
      'UtensilsCrossed',
      'Coffee',
      'Apple',
      'CookingPot',
      'Wine',
      'CakeSlice',
      'Truck',
    ],
    transportation: [
      'Car',
      'Fuel',
      'Bus',
      'Plane',
      'CarTaxiFront',
      'ParkingCircle',
      'Settings',
      'FileShield',
      'Bike',
    ],
    healthAndWellness: [
      'HeartPulse',
      'Pill',
      'Hospital',
      'Tooth',
      'Glasses',
      'BrainCircuit',
      'Dumbbell',
      'Plus',
    ],
    personalAndEducation: [
      'Shirt',
      'ShoppingBag',
      'Scissors',
      'Sparkles',
      'GraduationCap',
      'BookOpen',
      'Laptop',
      'Newspaper',
    ],
    leisureAndEntertainment: [
      'Popcorn',
      'Theater',
      'Gamepad2',
      'Music',
      'Plane',
      'Tent',
      'Camera',
      'Ticket',
    ],
    familyAndKids: ['Baby', 'ToyBrick', 'School', 'Stethoscope', 'Users'],
    financeAndFees: [
      'CreditCard',
      'Receipt',
      'Landmark',
      'ArrowDownCircle',
      'Handshake',
      'AreaChart',
    ],
    pets: ['PawPrint', 'Dog', 'Cat', 'Bone', 'Stethoscope'],
  },
}

export const expenses = [...new Set(Object.values(lucideIcons.expenses).flat())]

export const incomes = lucideIcons.income
